language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 300
  model_confidence: linear_norm
  constrain_similarities: True
policies:
- name: TEDPolicy
  max_history: 10
  epochs: 100
  constrain_similarities: true
  batch_size:
  - 32
  - 64
- max_history: 6
  name: AugmentedMemoizationPolicy
- core_threshold: 0.3
  name: RulePolicy